# Generated by Django 4.1.4 on 2023-01-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_roomid_participants_classroom_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='classroom_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='user_id',
            new_name='user',
        ),
    ]
