# Generated by Django 4.1.4 on 2023-01-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_pictures"),
    ]

    operations = [
        migrations.AddField(
            model_name="pictures",
            name="picture",
            field=models.ImageField(blank=True, upload_to="my_picture"),
        ),
    ]
