# Generated by Django 4.1.4 on 2023-01-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_pictures_picture"),
    ]

    operations = [
        migrations.RenameField(model_name="pictures", old_name="des", new_name="name",),
    ]
