# Generated by Django 4.1.4 on 2023-01-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_des_pictures_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="pictures", name="name",),
        migrations.AlterField(
            model_name="pictures",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="my_picture"),
        ),
    ]
