# Generated by Django 4.1.4 on 2023-01-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_pictures_name_alter_pictures_picture"),
    ]

    operations = [
        migrations.RemoveField(model_name="pictures", name="picture",),
        migrations.AddField(
            model_name="pictures",
            name="image",
            field=models.ImageField(blank=True, upload_to="my_picture"),
        ),
        migrations.AddField(
            model_name="pictures",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
