# Generated by Django 4.1.4 on 2023-01-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_pictures_picture_pictures_image_pictures_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pictures",
            name="image",
            field=models.ImageField(blank=True, upload_to="my_picture/"),
        ),
    ]
