# Generated by Django 4.1.4 on 2023-01-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_pictures_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="pictures", name="name",),
    ]
